upstream model_backend {
    server ml-service-v1:8000 weight=100;
}

server {
    listen 80;

    location / {
        proxy_pass http://model_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
